site:
  name: GlowGetter Reviews
  site: 'https://glowgetterreviews.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: googlesiteverificationid

# Default SEO metadata
metadata:
  title:
    default: GlowGetter Reviews - Salon Testimonials
    template: '%s â€” GlowGetter Reviews'
  description: "Collect & showcase stunning client testimonials for your hair salon. Boost bookings & build trust with GlowGetter Reviews."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: GlowGetter Reviews
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@saashandle'
    site: '@saashandle'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6
    post: { isEnabled: true, permalink: '/%slug%', robots: { index: true } }
    list: { isEnabled: false, pathname: 'blog', robots: { index: true } }
    category: { isEnabled: false, pathname: 'category', robots: { index: true } }
    tag: { isEnabled: false, pathname: 'tag', robots: { index: false } }
    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics: { id: null }

ui:
  theme: 'light:only'
